import Navbar from "@/components/Navbar";
import styles from "./layout.module.css";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className={styles.navbar}>
                    <Navbar />
                </div>
                {children}
            </body>
        </html>
    );
}
